var annotated_dup =
[
    [ "GsCompute", "namespace_gs_compute.html", [
      [ "GsDataParallelPrimitives", "class_gs_compute_1_1_gs_data_parallel_primitives.html", "class_gs_compute_1_1_gs_data_parallel_primitives" ],
      [ "GsDevice", "class_gs_compute_1_1_gs_device.html", "class_gs_compute_1_1_gs_device" ],
      [ "GsDeviceManager", "class_gs_compute_1_1_gs_device_manager.html", "class_gs_compute_1_1_gs_device_manager" ],
      [ "GsDeviceProperties", "struct_gs_compute_1_1_gs_device_properties.html", "struct_gs_compute_1_1_gs_device_properties" ]
    ] ],
    [ "GsGraphics", "namespace_gs_graphics.html", [
      [ "GsGraphicsCore", "class_gs_graphics_1_1_gs_graphics_core.html", "class_gs_graphics_1_1_gs_graphics_core" ],
      [ "GsGraphicsUtils", "class_gs_graphics_1_1_gs_graphics_utils.html", null ],
      [ "GsIGraphicsObject", "class_gs_graphics_1_1_gs_i_graphics_object.html", "class_gs_graphics_1_1_gs_i_graphics_object" ],
      [ "GsShaderProgram", "class_gs_graphics_1_1_gs_shader_program.html", "class_gs_graphics_1_1_gs_shader_program" ]
    ] ],
    [ "GvCache", "namespace_gv_cache.html", [
      [ "GsBaseCacheManager", "class_gv_cache_1_1_gs_base_cache_manager.html", "class_gv_cache_1_1_gs_base_cache_manager" ],
      [ "GsCacheElementManager", "class_gv_cache_1_1_gs_cache_element_manager.html", "class_gv_cache_1_1_gs_cache_element_manager" ],
      [ "GsCacheHelper", "class_gv_cache_1_1_gs_cache_helper.html", "class_gv_cache_1_1_gs_cache_helper" ],
      [ "GsCacheManager", "class_gv_cache_1_1_gs_cache_manager.html", "class_gv_cache_1_1_gs_cache_manager" ],
      [ "GsCacheManagerKernel", "struct_gv_cache_1_1_gs_cache_manager_kernel.html", "struct_gv_cache_1_1_gs_cache_manager_kernel" ],
      [ "GsCacheManagerResources", "class_gv_cache_1_1_gs_cache_manager_resources.html", null ],
      [ "GsDataCacheManager", "class_gv_cache_1_1_gs_data_cache_manager.html", "class_gv_cache_1_1_gs_data_cache_manager" ],
      [ "GsGLCacheManager", "class_gv_cache_1_1_gs_g_l_cache_manager.html", "class_gv_cache_1_1_gs_g_l_cache_manager" ],
      [ "GsICacheManager", "class_gv_cache_1_1_gs_i_cache_manager.html", "class_gv_cache_1_1_gs_i_cache_manager" ],
      [ "GsNodeCacheManager", "class_gv_cache_1_1_gs_node_cache_manager.html", "class_gv_cache_1_1_gs_node_cache_manager" ]
    ] ],
    [ "GvCore", "namespace_gv_core.html", [
      [ "Array3D", "class_gv_core_1_1_array3_d.html", "class_gv_core_1_1_array3_d" ],
      [ "DataChannelSize", "struct_gv_core_1_1_data_channel_size.html", null ],
      [ "DataChannelType", "struct_gv_core_1_1_data_channel_type.html", "struct_gv_core_1_1_data_channel_type" ],
      [ "DataChannelUnitValue", "struct_gv_core_1_1_data_channel_unit_value.html", "struct_gv_core_1_1_data_channel_unit_value" ],
      [ "DataNumChannels", "struct_gv_core_1_1_data_num_channels.html", null ],
      [ "DataStruct", "struct_gv_core_1_1_data_struct.html", "struct_gv_core_1_1_data_struct" ],
      [ "DataTotalChannelSize", "struct_gv_core_1_1_data_total_channel_size.html", null ],
      [ "DataTotalChannelSize< TList, 0 >", "struct_gv_core_1_1_data_total_channel_size_3_01_t_list_00_010_01_4.html", null ],
      [ "equal_to_zero", "struct_gv_core_1_1equal__to__zero.html", "struct_gv_core_1_1equal__to__zero" ],
      [ "GPUPool", "class_gv_core_1_1_g_p_u_pool.html", "class_gv_core_1_1_g_p_u_pool" ],
      [ "GPUPool_KernelPoolFromHostPool", "struct_gv_core_1_1_g_p_u_pool___kernel_pool_from_host_pool.html", null ],
      [ "GPUPool_KernelPoolFromHostPool< Array3D, TList >", "struct_gv_core_1_1_g_p_u_pool___kernel_pool_from_host_pool_3_01_array3_d_00_01_t_list_01_4.html", "struct_gv_core_1_1_g_p_u_pool___kernel_pool_from_host_pool_3_01_array3_d_00_01_t_list_01_4" ],
      [ "GPUPool_KernelPoolFromHostPool< GsDeviceTexturingMemory, TList >", "struct_gv_core_1_1_g_p_u_pool___kernel_pool_from_host_pool_3_01_gs_device_texturing_memory_00_01_t_list_01_4.html", "struct_gv_core_1_1_g_p_u_pool___kernel_pool_from_host_pool_3_01_gs_device_texturing_memory_00_01_t_list_01_4" ],
      [ "GPUPool_KernelPoolFromHostPool< GsLinearMemory, TList >", "struct_gv_core_1_1_g_p_u_pool___kernel_pool_from_host_pool_3_01_gs_linear_memory_00_01_t_list_01_4.html", "struct_gv_core_1_1_g_p_u_pool___kernel_pool_from_host_pool_3_01_gs_linear_memory_00_01_t_list_01_4" ],
      [ "GPUPool_TypeAtChannel", "struct_gv_core_1_1_g_p_u_pool___type_at_channel.html", "struct_gv_core_1_1_g_p_u_pool___type_at_channel" ],
      [ "GPUPoolChannelUnitPointer", "struct_gv_core_1_1_g_p_u_pool_channel_unit_pointer.html", "struct_gv_core_1_1_g_p_u_pool_channel_unit_pointer" ],
      [ "GPUPoolChannelUnitValue", "struct_gv_core_1_1_g_p_u_pool_channel_unit_value.html", "struct_gv_core_1_1_g_p_u_pool_channel_unit_value" ],
      [ "GPUPoolHost", "class_gv_core_1_1_g_p_u_pool_host.html", "class_gv_core_1_1_g_p_u_pool_host" ],
      [ "GPUPoolKernel", "class_gv_core_1_1_g_p_u_pool_kernel.html", "class_gv_core_1_1_g_p_u_pool_kernel" ],
      [ "GsDeviceTexturingMemory", "class_gv_core_1_1_gs_device_texturing_memory.html", "class_gv_core_1_1_gs_device_texturing_memory" ],
      [ "GsDeviceTexturingMemoryKernel", "class_gv_core_1_1_gs_device_texturing_memory_kernel.html", "class_gv_core_1_1_gs_device_texturing_memory_kernel" ],
      [ "GsIPipeline", "class_gv_core_1_1_gs_i_pipeline.html", "class_gv_core_1_1_gs_i_pipeline" ],
      [ "GsIPriorityPoliciesManagerKernel", "class_gv_core_1_1_gs_i_priority_policies_manager_kernel.html", null ],
      [ "GsIProvider", "class_gv_core_1_1_gs_i_provider.html", "class_gv_core_1_1_gs_i_provider" ],
      [ "GsIProviderKernel", "class_gv_core_1_1_gs_i_provider_kernel.html", "class_gv_core_1_1_gs_i_provider_kernel" ],
      [ "GsISerializable", "class_gv_core_1_1_gs_i_serializable.html", "class_gv_core_1_1_gs_i_serializable" ],
      [ "GsLinearMemory", "class_gv_core_1_1_gs_linear_memory.html", "class_gv_core_1_1_gs_linear_memory" ],
      [ "GsLinearMemoryKernel", "class_gv_core_1_1_gs_linear_memory_kernel.html", "class_gv_core_1_1_gs_linear_memory_kernel" ],
      [ "GsLocalizationInfo", "struct_gv_core_1_1_gs_localization_info.html", "struct_gv_core_1_1_gs_localization_info" ],
      [ "GsPriorityParameters", "struct_gv_core_1_1_gs_priority_parameters.html", "struct_gv_core_1_1_gs_priority_parameters" ],
      [ "GsProvider", "class_gv_core_1_1_gs_provider.html", "class_gv_core_1_1_gs_provider" ],
      [ "GsVec1D", "struct_gv_core_1_1_gs_vec1_d.html", null ],
      [ "GsVec3D", "struct_gv_core_1_1_gs_vec3_d.html", null ],
      [ "GsVersion", "class_gv_core_1_1_gs_version.html", null ],
      [ "GvDataTypeInspector", "struct_gv_core_1_1_gv_data_type_inspector.html", "struct_gv_core_1_1_gv_data_type_inspector" ],
      [ "GvLocalizationCode", "class_gv_core_1_1_gv_localization_code.html", "class_gv_core_1_1_gv_localization_code" ],
      [ "GvLocalizationDepth", "class_gv_core_1_1_gv_localization_depth.html", "class_gv_core_1_1_gv_localization_depth" ],
      [ "IDivUp", "struct_gv_core_1_1_i_div_up.html", null ],
      [ "IsFloatFormat", "struct_gv_core_1_1_is_float_format.html", null ],
      [ "IsFloatFormat< float >", "struct_gv_core_1_1_is_float_format_3_01float_01_4.html", null ],
      [ "IsFloatFormat< float2 >", "struct_gv_core_1_1_is_float_format_3_01float2_01_4.html", null ],
      [ "IsFloatFormat< float3 >", "struct_gv_core_1_1_is_float_format_3_01float3_01_4.html", null ],
      [ "IsFloatFormat< float4 >", "struct_gv_core_1_1_is_float_format_3_01float4_01_4.html", null ],
      [ "IsFloatFormat< half4 >", "struct_gv_core_1_1_is_float_format_3_01half4_01_4.html", null ],
      [ "Log2", "struct_gv_core_1_1_log2.html", null ],
      [ "Log2< 1 >", "struct_gv_core_1_1_log2_3_011_01_4.html", null ],
      [ "Log2< 3 >", "struct_gv_core_1_1_log2_3_013_01_4.html", null ],
      [ "Max", "struct_gv_core_1_1_max.html", null ],
      [ "Min", "struct_gv_core_1_1_min.html", null ],
      [ "not_equal_to_zero", "struct_gv_core_1_1not__equal__to__zero.html", "struct_gv_core_1_1not__equal__to__zero" ],
      [ "PageTable", "struct_gv_core_1_1_page_table.html", "struct_gv_core_1_1_page_table" ],
      [ "PageTableBricks", "struct_gv_core_1_1_page_table_bricks.html", "struct_gv_core_1_1_page_table_bricks" ],
      [ "PageTableBricksKernel", "struct_gv_core_1_1_page_table_bricks_kernel.html", "struct_gv_core_1_1_page_table_bricks_kernel" ],
      [ "PageTableKernel", "struct_gv_core_1_1_page_table_kernel.html", "struct_gv_core_1_1_page_table_kernel" ],
      [ "PageTableNodes", "struct_gv_core_1_1_page_table_nodes.html", "struct_gv_core_1_1_page_table_nodes" ],
      [ "PageTableNodesKernel", "struct_gv_core_1_1_page_table_nodes_kernel.html", "struct_gv_core_1_1_page_table_nodes_kernel" ],
      [ "ReplaceTypeTemplated", "struct_gv_core_1_1_replace_type_templated.html", null ],
      [ "ReplaceTypeTemplated< Loki::NullType, RT >", "struct_gv_core_1_1_replace_type_templated_3_01_loki_1_1_null_type_00_01_r_t_01_4.html", "struct_gv_core_1_1_replace_type_templated_3_01_loki_1_1_null_type_00_01_r_t_01_4" ],
      [ "ReplaceTypeTemplated< Loki::Typelist< T, Tail >, RT >", "struct_gv_core_1_1_replace_type_templated_3_01_loki_1_1_typelist_3_01_t_00_01_tail_01_4_00_01_r_t_01_4.html", "struct_gv_core_1_1_replace_type_templated_3_01_loki_1_1_typelist_3_01_t_00_01_tail_01_4_00_01_r_t_01_4" ],
      [ "StaticLoop", "class_gv_core_1_1_static_loop.html", null ],
      [ "StaticLoop< SFunctor, -1 >", "class_gv_core_1_1_static_loop_3_01_s_functor_00_01-1_01_4.html", null ],
      [ "StaticLoopCallStatic", "class_gv_core_1_1_static_loop_call_static.html", null ],
      [ "StaticLoopCallStatic< SFunctor, -1 >", "class_gv_core_1_1_static_loop_call_static_3_01_s_functor_00_01-1_01_4.html", null ]
    ] ],
    [ "GvPerfMon", "namespace_gv_perf_mon.html", [
      [ "CUDAPerfMon", "class_gv_perf_mon_1_1_c_u_d_a_perf_mon.html", "class_gv_perf_mon_1_1_c_u_d_a_perf_mon" ],
      [ "GsDevicePerformanceTimer", "class_gv_perf_mon_1_1_gs_device_performance_timer.html", "class_gv_perf_mon_1_1_gs_device_performance_timer" ],
      [ "GsPerformanceTimer", "class_gv_perf_mon_1_1_gs_performance_timer.html", "class_gv_perf_mon_1_1_gs_performance_timer" ]
    ] ],
    [ "GvRendering", "namespace_gv_rendering.html", [
      [ "GsBrickVisitorKernel", "class_gv_rendering_1_1_gs_brick_visitor_kernel.html", null ],
      [ "GsGraphicsInteroperabiltyHandler", "class_gv_rendering_1_1_gs_graphics_interoperabilty_handler.html", "class_gv_rendering_1_1_gs_graphics_interoperabilty_handler" ],
      [ "GsGraphicsResource", "class_gv_rendering_1_1_gs_graphics_resource.html", "class_gv_rendering_1_1_gs_graphics_resource" ],
      [ "GsGraphicsResourceManager", "class_gv_rendering_1_1_gs_graphics_resource_manager.html", "class_gv_rendering_1_1_gs_graphics_resource_manager" ],
      [ "GsIRenderer", "class_gv_rendering_1_1_gs_i_renderer.html", "class_gv_rendering_1_1_gs_i_renderer" ],
      [ "GsIRenderShader", "class_gv_rendering_1_1_gs_i_render_shader.html", "class_gv_rendering_1_1_gs_i_render_shader" ],
      [ "GsNodeVisitorKernel", "class_gv_rendering_1_1_gs_node_visitor_kernel.html", null ],
      [ "GsQualityRendererCUDA", "class_gv_rendering_1_1_gs_quality_renderer_c_u_d_a.html", "class_gv_rendering_1_1_gs_quality_renderer_c_u_d_a" ],
      [ "GsRenderer", "class_gv_rendering_1_1_gs_renderer.html", "class_gv_rendering_1_1_gs_renderer" ],
      [ "GsRendererContext", "struct_gv_rendering_1_1_gs_renderer_context.html", "struct_gv_rendering_1_1_gs_renderer_context" ],
      [ "GsRendererCUDA", "class_gv_rendering_1_1_gs_renderer_c_u_d_a.html", "class_gv_rendering_1_1_gs_renderer_c_u_d_a" ],
      [ "GsRendererGLSL", "class_gv_rendering_1_1_gs_renderer_g_l_s_l.html", "class_gv_rendering_1_1_gs_renderer_g_l_s_l" ],
      [ "GsRendererKernel", "class_gv_rendering_1_1_gs_renderer_kernel.html", null ],
      [ "GsSamplerKernel", "struct_gv_rendering_1_1_gs_sampler_kernel.html", "struct_gv_rendering_1_1_gs_sampler_kernel" ]
    ] ],
    [ "GvStructure", "namespace_gv_structure.html", [
      [ "GsDataProductionManager", "class_gv_structure_1_1_gs_data_production_manager.html", "class_gv_structure_1_1_gs_data_production_manager" ],
      [ "GsDataProductionManagerKernel", "struct_gv_structure_1_1_gs_data_production_manager_kernel.html", "struct_gv_structure_1_1_gs_data_production_manager_kernel" ],
      [ "GsIDataProductionManager", "class_gv_structure_1_1_gs_i_data_production_manager.html", "class_gv_structure_1_1_gs_i_data_production_manager" ],
      [ "GsIDataStructure", "class_gv_structure_1_1_gs_i_data_structure.html", "class_gv_structure_1_1_gs_i_data_structure" ],
      [ "GsIReader", "class_gv_structure_1_1_gs_i_reader.html", "class_gv_structure_1_1_gs_i_reader" ],
      [ "GsIWriter", "class_gv_structure_1_1_gs_i_writer.html", "class_gv_structure_1_1_gs_i_writer" ],
      [ "GsNode", "struct_gv_structure_1_1_gs_node.html", "struct_gv_structure_1_1_gs_node" ],
      [ "GsProductionStatistics", "struct_gv_structure_1_1_gs_production_statistics.html", "struct_gv_structure_1_1_gs_production_statistics" ],
      [ "GsReader", "class_gv_structure_1_1_gs_reader.html", "class_gv_structure_1_1_gs_reader" ],
      [ "GsVolumeTree", "struct_gv_structure_1_1_gs_volume_tree.html", "struct_gv_structure_1_1_gs_volume_tree" ],
      [ "GsWriter", "class_gv_structure_1_1_gs_writer.html", "class_gv_structure_1_1_gs_writer" ],
      [ "VolTreeBrickAddress", "struct_gv_structure_1_1_vol_tree_brick_address.html", "struct_gv_structure_1_1_vol_tree_brick_address" ],
      [ "VolTreeNodeAddress", "struct_gv_structure_1_1_vol_tree_node_address.html", "struct_gv_structure_1_1_vol_tree_node_address" ],
      [ "VolumeTreeKernel", "struct_gv_structure_1_1_volume_tree_kernel.html", "struct_gv_structure_1_1_volume_tree_kernel" ]
    ] ],
    [ "GvUtils", "namespace_gv_utils.html", [
      [ "GsBrickLoaderChannelInitializer", "struct_gv_utils_1_1_gs_brick_loader_channel_initializer.html", "struct_gv_utils_1_1_gs_brick_loader_channel_initializer" ],
      [ "GsCommonGraphicsPass", "class_gv_utils_1_1_gs_common_graphics_pass.html", "class_gv_utils_1_1_gs_common_graphics_pass" ],
      [ "GsCommonShaderKernel", "class_gv_utils_1_1_gs_common_shader_kernel.html", "class_gv_utils_1_1_gs_common_shader_kernel" ],
      [ "GsDataLoader", "class_gv_utils_1_1_gs_data_loader.html", "class_gv_utils_1_1_gs_data_loader" ],
      [ "GsEnvironment", "class_gv_utils_1_1_gs_environment.html", "class_gv_utils_1_1_gs_environment" ],
      [ "GsFileNameBuilder", "class_gv_utils_1_1_gs_file_name_builder.html", "class_gv_utils_1_1_gs_file_name_builder" ],
      [ "GsIDataLoader", "class_gv_utils_1_1_gs_i_data_loader.html", "class_gv_utils_1_1_gs_i_data_loader" ],
      [ "GsImageDownscaling", "class_gv_utils_1_1_gs_image_downscaling.html", "class_gv_utils_1_1_gs_image_downscaling" ],
      [ "GsMaterial", "class_gv_utils_1_1_gs_material.html", "class_gv_utils_1_1_gs_material" ],
      [ "GsMaterialKernel", "class_gv_utils_1_1_gs_material_kernel.html", "class_gv_utils_1_1_gs_material_kernel" ],
      [ "GsNoise", "class_gv_utils_1_1_gs_noise.html", "class_gv_utils_1_1_gs_noise" ],
      [ "GsNoiseKernel", "class_gv_utils_1_1_gs_noise_kernel.html", null ],
      [ "GsPipeline", "class_gv_utils_1_1_gs_pipeline.html", "class_gv_utils_1_1_gs_pipeline" ],
      [ "GsPluginInterface", "class_gv_utils_1_1_gs_plugin_interface.html", "class_gv_utils_1_1_gs_plugin_interface" ],
      [ "GsPluginManager", "class_gv_utils_1_1_gs_plugin_manager.html", "class_gv_utils_1_1_gs_plugin_manager" ],
      [ "GsProxyGeometry", "class_gv_utils_1_1_gs_proxy_geometry.html", "class_gv_utils_1_1_gs_proxy_geometry" ],
      [ "GsProxyGeometryHandler", "class_gv_utils_1_1_gs_proxy_geometry_handler.html", "class_gv_utils_1_1_gs_proxy_geometry_handler" ],
      [ "GsRayMap", "class_gv_utils_1_1_gs_ray_map.html", "class_gv_utils_1_1_gs_ray_map" ],
      [ "GsShaderManager", "class_gv_utils_1_1_gs_shader_manager.html", "class_gv_utils_1_1_gs_shader_manager" ],
      [ "GsSimpleHostProducer", "class_gv_utils_1_1_gs_simple_host_producer.html", "class_gv_utils_1_1_gs_simple_host_producer" ],
      [ "GsSimpleHostShader", "class_gv_utils_1_1_gs_simple_host_shader.html", "class_gv_utils_1_1_gs_simple_host_shader" ],
      [ "GsSimplePipeline", "class_gv_utils_1_1_gs_simple_pipeline.html", "class_gv_utils_1_1_gs_simple_pipeline" ],
      [ "GsSimplePriorityPoliciesManagerKernel", "class_gv_utils_1_1_gs_simple_priority_policies_manager_kernel.html", null ],
      [ "GsTransferFunction", "class_gv_utils_1_1_gs_transfer_function.html", "class_gv_utils_1_1_gs_transfer_function" ],
      [ "GsViewFrustumCuller", "class_gv_utils_1_1_gs_view_frustum_culler.html", "class_gv_utils_1_1_gs_view_frustum_culler" ],
      [ "GvDepthOfFieldKernel", "class_gv_utils_1_1_gv_depth_of_field_kernel.html", null ],
      [ "GvLightingModel", "class_gv_utils_1_1_gv_lighting_model.html", null ],
      [ "GvPreIntegratedTransferFunction", "class_gv_utils_1_1_gv_pre_integrated_transfer_function.html", "class_gv_utils_1_1_gv_pre_integrated_transfer_function" ]
    ] ],
    [ "GvVoxelizer", "namespace_gv_voxelizer.html", [
      [ "GsDataStructureIOHandler", "class_gv_voxelizer_1_1_gs_data_structure_i_o_handler.html", "class_gv_voxelizer_1_1_gs_data_structure_i_o_handler" ],
      [ "GsDataStructureMipmapGenerator", "class_gv_voxelizer_1_1_gs_data_structure_mipmap_generator.html", "class_gv_voxelizer_1_1_gs_data_structure_mipmap_generator" ],
      [ "GsDataTypeHandler", "class_gv_voxelizer_1_1_gs_data_type_handler.html", "class_gv_voxelizer_1_1_gs_data_type_handler" ],
      [ "GsIRAWFileReader", "class_gv_voxelizer_1_1_gs_i_r_a_w_file_reader.html", "class_gv_voxelizer_1_1_gs_i_r_a_w_file_reader" ]
    ] ],
    [ "float3x4", "structfloat3x4.html", "structfloat3x4" ],
    [ "float4x4", "structfloat4x4.html", "structfloat4x4" ],
    [ "GsOracleRegionInfo", "class_gs_oracle_region_info.html", "class_gs_oracle_region_info" ],
    [ "GvPriorityPoliciesManagerKernel", "class_gv_priority_policies_manager_kernel.html", null ],
    [ "half2", "structhalf2.html", "structhalf2" ],
    [ "half4", "structhalf4.html", "structhalf4" ],
    [ "NullType", "struct_null_type.html", null ],
    [ "ProducerLoad", "class_producer_load.html", null ],
    [ "SampleCore", "class_sample_core.html", "class_sample_core" ]
];