
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:20 (project)"
    message: |
      The system is: Windows - 10.0.22631 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:20 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Microsoft (R) Build Engine version 16.11.2+f32259642 pour .NET Framework
      Copyright (C) Microsoft Corporation. Tous droits réservés.
      
      La génération a démarré 08/02/2024 11:20:50.
      Projet "C:\\Users\\rolan\\Desktop\\GigaVoxelsDev\\Generated_VC16_x64\\Tools\\CMakeFiles\\3.27.6\\CompilerIdC\\CompilerIdC.vcxproj" sur le noud 1 (cibles par défaut).
      PrepareForBuild:
        Création du répertoire "Debug\\".
        Création du répertoire "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        Création de "Debug\\CompilerIdC.tlog\\unsuccessfulbuild", car "AlwaysCreate" a été spécifié.
      ClCompile:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc142.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> C:\\Users\\rolan\\Desktop\\GigaVoxelsDev\\Generated_VC16_x64\\Tools\\CMakeFiles\\3.27.6\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Suppression du fichier "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
        Mise à jour de l'horodatage "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate".
      Génération du projet "C:\\Users\\rolan\\Desktop\\GigaVoxelsDev\\Generated_VC16_x64\\Tools\\CMakeFiles\\3.27.6\\CompilerIdC\\CompilerIdC.vcxproj" terminée (cibles par défaut).
      
      La génération a réussi.
          0 Avertissement(s)
          0 Erreur(s)
      
      Temps écoulé 00:00:00.96
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        C:/Users/rolan/Desktop/GigaVoxelsDev/Generated_VC16_x64/Tools/CMakeFiles/3.27.6/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:20 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Microsoft (R) Build Engine version 16.11.2+f32259642 pour .NET Framework
      Copyright (C) Microsoft Corporation. Tous droits réservés.
      
      La génération a démarré 08/02/2024 11:20:52.
      Projet "C:\\Users\\rolan\\Desktop\\GigaVoxelsDev\\Generated_VC16_x64\\Tools\\CMakeFiles\\3.27.6\\CompilerIdCXX\\CompilerIdCXX.vcxproj" sur le noud 1 (cibles par défaut).
      PrepareForBuild:
        Création du répertoire "Debug\\".
        Création du répertoire "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        Création de "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild", car "AlwaysCreate" a été spécifié.
      ClCompile:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc142.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> C:\\Users\\rolan\\Desktop\\GigaVoxelsDev\\Generated_VC16_x64\\Tools\\CMakeFiles\\3.27.6\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Suppression du fichier "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
        Mise à jour de l'horodatage "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate".
      Génération du projet "C:\\Users\\rolan\\Desktop\\GigaVoxelsDev\\Generated_VC16_x64\\Tools\\CMakeFiles\\3.27.6\\CompilerIdCXX\\CompilerIdCXX.vcxproj" terminée (cibles par défaut).
      
      La génération a réussi.
          0 Avertissement(s)
          0 Erreur(s)
      
      Temps écoulé 00:00:00.98
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        C:/Users/rolan/Desktop/GigaVoxelsDev/Generated_VC16_x64/Tools/CMakeFiles/3.27.6/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:20 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/rolan/Desktop/GigaVoxelsDev/Generated_VC16_x64/Tools/CMakeFiles/CMakeScratch/TryCompile-c2348j"
      binary: "C:/Users/rolan/Desktop/GigaVoxelsDev/Generated_VC16_x64/Tools/CMakeFiles/CMakeScratch/TryCompile-c2348j"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/rolan/Desktop/GigaVoxelsDev/Generated_VC16_x64/Tools/CMakeFiles/CMakeScratch/TryCompile-c2348j'
        
        Run Build Command(s): "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe" cmTC_821b5.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:n
        Microsoft (R) Build Engine version 16.11.2+f32259642 pour .NET Framework
        Copyright (C) Microsoft Corporation. Tous droits réservés.
        
        La génération a démarré 08/02/2024 11:20:53.
        Projet "C:\\Users\\rolan\\Desktop\\GigaVoxelsDev\\Generated_VC16_x64\\Tools\\CMakeFiles\\CMakeScratch\\TryCompile-c2348j\\cmTC_821b5.vcxproj" sur le noud 1 (cibles par défaut).
        PrepareForBuild:
          Création du répertoire "cmTC_821b5.dir\\Debug\\".
          Création du répertoire "C:\\Users\\rolan\\Desktop\\GigaVoxelsDev\\Generated_VC16_x64\\Tools\\CMakeFiles\\CMakeScratch\\TryCompile-c2348j\\Debug\\".
          Création du répertoire "cmTC_821b5.dir\\Debug\\cmTC_821b5.tlog\\".
        InitializeBuildStatus:
          Création de "cmTC_821b5.dir\\Debug\\cmTC_821b5.tlog\\unsuccessfulbuild", car "AlwaysCreate" a été spécifié.
        ClCompile:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_821b5.dir\\Debug\\\\" /Fd"cmTC_821b5.dir\\Debug\\vc142.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.27\\Modules\\CMakeCCompilerABI.c"
          Compilateur d'optimisation Microsoft (R) C/C++ version 19.29.30153 pour x64
          Copyright (C) Microsoft Corporation. Tous droits réservés.
          CMakeCCompilerABI.c
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_821b5.dir\\Debug\\\\" /Fd"cmTC_821b5.dir\\Debug\\vc142.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.27\\Modules\\CMakeCCompilerABI.c"
        Link:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\rolan\\Desktop\\GigaVoxelsDev\\Generated_VC16_x64\\Tools\\CMakeFiles\\CMakeScratch\\TryCompile-c2348j\\Debug\\cmTC_821b5.exe" /INCREMENTAL /ILK:"cmTC_821b5.dir\\Debug\\cmTC_821b5.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/rolan/Desktop/GigaVoxelsDev/Generated_VC16_x64/Tools/CMakeFiles/CMakeScratch/TryCompile-c2348j/Debug/cmTC_821b5.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/rolan/Desktop/GigaVoxelsDev/Generated_VC16_x64/Tools/CMakeFiles/CMakeScratch/TryCompile-c2348j/Debug/cmTC_821b5.lib" /MACHINE:X64  /machine:x64 cmTC_821b5.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_821b5.vcxproj -> C:\\Users\\rolan\\Desktop\\GigaVoxelsDev\\Generated_VC16_x64\\Tools\\CMakeFiles\\CMakeScratch\\TryCompile-c2348j\\Debug\\cmTC_821b5.exe
        FinalizeBuildStatus:
          Suppression du fichier "cmTC_821b5.dir\\Debug\\cmTC_821b5.tlog\\unsuccessfulbuild".
          Mise à jour de l'horodatage "cmTC_821b5.dir\\Debug\\cmTC_821b5.tlog\\cmTC_821b5.lastbuildstate".
        Génération du projet "C:\\Users\\rolan\\Desktop\\GigaVoxelsDev\\Generated_VC16_x64\\Tools\\CMakeFiles\\CMakeScratch\\TryCompile-c2348j\\cmTC_821b5.vcxproj" terminée (cibles par défaut).
        
        La génération a réussi.
            0 Avertissement(s)
            0 Erreur(s)
        
        Temps écoulé 00:00:00.99
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:20 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/Users/rolan/Desktop/GigaVoxelsDev/Generated_VC16_x64/Tools/CMakeFiles/CMakeScratch/TryCompile-k1fkbt"
      binary: "C:/Users/rolan/Desktop/GigaVoxelsDev/Generated_VC16_x64/Tools/CMakeFiles/CMakeScratch/TryCompile-k1fkbt"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/rolan/Desktop/GigaVoxelsDev/Generated_VC16_x64/Tools/CMakeFiles/CMakeScratch/TryCompile-k1fkbt'
        
        Run Build Command(s): "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe" cmTC_d17b2.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:n
        Microsoft (R) Build Engine version 16.11.2+f32259642 pour .NET Framework
        Copyright (C) Microsoft Corporation. Tous droits réservés.
        
        La génération a démarré 08/02/2024 11:20:55.
        Projet "C:\\Users\\rolan\\Desktop\\GigaVoxelsDev\\Generated_VC16_x64\\Tools\\CMakeFiles\\CMakeScratch\\TryCompile-k1fkbt\\cmTC_d17b2.vcxproj" sur le noud 1 (cibles par défaut).
        PrepareForBuild:
          Création du répertoire "cmTC_d17b2.dir\\Debug\\".
          Création du répertoire "C:\\Users\\rolan\\Desktop\\GigaVoxelsDev\\Generated_VC16_x64\\Tools\\CMakeFiles\\CMakeScratch\\TryCompile-k1fkbt\\Debug\\".
          Création du répertoire "cmTC_d17b2.dir\\Debug\\cmTC_d17b2.tlog\\".
        InitializeBuildStatus:
          Création de "cmTC_d17b2.dir\\Debug\\cmTC_d17b2.tlog\\unsuccessfulbuild", car "AlwaysCreate" a été spécifié.
        ClCompile:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_d17b2.dir\\Debug\\\\" /Fd"cmTC_d17b2.dir\\Debug\\vc142.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.27\\Modules\\CMakeCXXCompilerABI.cpp"
          Compilateur d'optimisation Microsoft (R) C/C++ version 19.29.30153 pour x64
          Copyright (C) Microsoft Corporation. Tous droits réservés.
          CMakeCXXCompilerABI.cpp
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_d17b2.dir\\Debug\\\\" /Fd"cmTC_d17b2.dir\\Debug\\vc142.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.27\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\rolan\\Desktop\\GigaVoxelsDev\\Generated_VC16_x64\\Tools\\CMakeFiles\\CMakeScratch\\TryCompile-k1fkbt\\Debug\\cmTC_d17b2.exe" /INCREMENTAL /ILK:"cmTC_d17b2.dir\\Debug\\cmTC_d17b2.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/rolan/Desktop/GigaVoxelsDev/Generated_VC16_x64/Tools/CMakeFiles/CMakeScratch/TryCompile-k1fkbt/Debug/cmTC_d17b2.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/rolan/Desktop/GigaVoxelsDev/Generated_VC16_x64/Tools/CMakeFiles/CMakeScratch/TryCompile-k1fkbt/Debug/cmTC_d17b2.lib" /MACHINE:X64  /machine:x64 cmTC_d17b2.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_d17b2.vcxproj -> C:\\Users\\rolan\\Desktop\\GigaVoxelsDev\\Generated_VC16_x64\\Tools\\CMakeFiles\\CMakeScratch\\TryCompile-k1fkbt\\Debug\\cmTC_d17b2.exe
        FinalizeBuildStatus:
          Suppression du fichier "cmTC_d17b2.dir\\Debug\\cmTC_d17b2.tlog\\unsuccessfulbuild".
          Mise à jour de l'horodatage "cmTC_d17b2.dir\\Debug\\cmTC_d17b2.tlog\\cmTC_d17b2.lastbuildstate".
        Génération du projet "C:\\Users\\rolan\\Desktop\\GigaVoxelsDev\\Generated_VC16_x64\\Tools\\CMakeFiles\\CMakeScratch\\TryCompile-k1fkbt\\cmTC_d17b2.vcxproj" terminée (cibles par défaut).
        
        La génération a réussi.
            0 Avertissement(s)
            0 Erreur(s)
        
        Temps écoulé 00:00:00.96
        
      exitCode: 0
...
